In [18]:
import numpy as np
import statistics as stats
Data = [15, 21, 29, 21, 15, 24, 32, 21, 15, 30]
mean_data = np.mean(Data)
print("Mean:", mean_data)
median_data = np.median(Data)
print("Median:", median_data)
mode_data = stats.mode(Data)
print("Mode:", mode_data)
variance_data = np.var(Data)  
print("Variance:", variance_data)
std_dev_data = np.std(Data) 
print("Standard Deviation:", std_dev_data)

Mean: 22.3
Median: 21.0
Mode: 15
Variance: 36.61
Standard Deviation: 6.050619802962338


In [20]:
import pandas as pd
df = pd.read_excel("robot_dataset(robot_dataset)_1.xlsx")
print(df.drop_duplicates().head(5))
mean_specific = df['Interaction_Count'].mean() 
print("\nMean of the specific column 'Interaction_Count':", mean_specific)

  Robot_ID   Task_Type Component_ID Sensor_Type            Sensor_Data  \
0  RBT_001  Inspection      CMP_460       LIDAR  1 (obstacle detected)   
1  RBT_002    Assembly      CMP_252     Thermal             85.3 (°C)   
2  RBT_003  Inspection      CMP_248     Thermal       92% (visual fit)   
3  RBT_004     Welding      CMP_433      Camera      98% (defect-free)   
4  RBT_005    Assembly      CMP_992      Camera       92% (visual fit)   

   Processing_Time (s)  Accuracy (%) Environmental_Status  \
0                 67.0          90.4               Stable   
1                 71.2          98.1               Stable   
2                 49.2          95.3             Unstable   
3                 74.5          90.2               Stable   
4                 64.5          97.2             Unstable   

   Energy_Consumption (kWh) Human_Intervention_Needed Obstacle_Detected  \
0                       2.2                        No               Yes   
1                       2.7           

In [21]:
import pandas as pd
df = pd.read_excel("robot_dataset(robot_dataset)_1.xlsx")
mean_specific = df['Interaction_Count'].mean() 
print("\nMean of the specific column 'Interaction_Count':", mean_specific)
total = df['Steps_Walked'].sum() 
print(f"The total of the column is: {total}")
max_value_column = df['Energy_Consumption (kWh)'].max() 
min_value_column = df['Energy_Consumption (kWh)'].min()
print(f"Maximum value in 'Energy_Consumption (kWh)': {max_value_column}")
print(f"Minimum value in 'Energy_Consumption (kWh): {min_value_column}") 
correlation = df['Steps_Walked'].corr(df['Energy_Consumption (kWh)']) 
print(f"The correlation between Steps_Walked and Energy_Consumption (kWh) is: {correlation}") 
variance = df['Learning_Sessions'].var() 
print(f"The variance of the 'Learning_Sessions' column is: {variance}")


Mean of the specific column 'Interaction_Count': 5.51
The total of the column is: 14379
Maximum value in 'Energy_Consumption (kWh)': 3.0
Minimum value in 'Energy_Consumption (kWh): 1.0
The correlation between Steps_Walked and Energy_Consumption (kWh) is: 0.0015478137393314488
The variance of the 'Learning_Sessions' column is: 391.9422845691382


In [19]:
name = "Alice"        
age = 25            
height = 5.6    
is_student = True    
print(f"My name is {name}, I am {age} years old, and my height is {height} feet.")
print(f"Am I a student? {is_student}")

My name is Alice, I am 25 years old, and my height is 5.6 feet.
Am I a student? True


In [1]:
number = int(input("Enter an integer: "))
if number > 0:
    print("The number is positive.")
elif number < 0:
    print("The number is negative.")
else:
    print("The number is zero.")


Enter an integer:  5


The number is positive.


In [2]:
number = int(input("Enter a number: "))
for i in range(1, 11):
    print(f"{number} x {i} = {number * i}")


Enter a number:  8


8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80


In [3]:
fruits = ["Apple", "Banana", "Orange", "Mango", "Grapes"]
print("Original list:", fruits)
fruits.append("Pineapple")
print("\nAfter appending a new fruit:", fruits)
fruits.remove("Banana")
print("\nAfter removing 'Banana':", fruits)
fruits.insert(1, "Strawberry")
print("\nAfter inserting 'Strawberry' at the second position:", fruits)
fruits.sort()
print("\nAfter sorting the list alphabetically:", fruits)
fruits.reverse()
print("\nAfter reversing the list:", fruits)
length = len(fruits)
print("\nLength of the list:", length)


Original list: ['Apple', 'Banana', 'Orange', 'Mango', 'Grapes']

After appending a new fruit: ['Apple', 'Banana', 'Orange', 'Mango', 'Grapes', 'Pineapple']

After removing 'Banana': ['Apple', 'Orange', 'Mango', 'Grapes', 'Pineapple']

After inserting 'Strawberry' at the second position: ['Apple', 'Strawberry', 'Orange', 'Mango', 'Grapes', 'Pineapple']

After sorting the list alphabetically: ['Apple', 'Grapes', 'Mango', 'Orange', 'Pineapple', 'Strawberry']

After reversing the list: ['Strawberry', 'Pineapple', 'Orange', 'Mango', 'Grapes', 'Apple']

Length of the list: 6


In [5]:
numbers = (5, 10, 15, 20, 25)
print("Original tuple:", numbers)
second_number = numbers[1]
print("Second number in the tuple:", second_number)
length = len(numbers)
print("Length of the tuple:", length)
check_number = 15
is_present = check_number in numbers
print(f"Is {check_number} in the tuple?", is_present)
numbers_list = list(numbers)
numbers_list.append(30)
numbers = tuple(numbers_list)  
print("Tuple after adding 30:", numbers)
count_10 = numbers.count(10)
print("Count of 10 in the tuple:", count_10)
index_20 = numbers.index(20)
print("Index of number 20 in the tuple:", index_20)


Original tuple: (5, 10, 15, 20, 25)
Second number in the tuple: 10
Length of the tuple: 5
Is 15 in the tuple? True
Tuple after adding 30: (5, 10, 15, 20, 25, 30)
Count of 10 in the tuple: 1
Index of number 20 in the tuple: 3


In [7]:
students_marks = {"Alice": 85, "Bob": 92, "Charlie": 78}
print("Original dictionary:", students_marks)
students_marks["David"] = 88
print("After adding David:", students_marks)
students_marks["Bob"] = 95
print("After updating Bob's marks:", students_marks)
del students_marks["Charlie"]
print("After removing Charlie:", students_marks)
alice_marks = students_marks.get("Alice")
print("Marks of Alice:", alice_marks)
is_bob_in_dict = "Bob" in students_marks
print("Is Bob in the dictionary?", is_bob_in_dict)
total_students = len(students_marks)
print("Total number of students:", total_students)
print("Student marks:")
for student, marks in students_marks.items():
    print(f"{student}: {marks}")


Original dictionary: {'Alice': 85, 'Bob': 92, 'Charlie': 78}
After adding David: {'Alice': 85, 'Bob': 92, 'Charlie': 78, 'David': 88}
After updating Bob's marks: {'Alice': 85, 'Bob': 95, 'Charlie': 78, 'David': 88}
After removing Charlie: {'Alice': 85, 'Bob': 95, 'David': 88}
Marks of Alice: 85
Is Bob in the dictionary? True
Total number of students: 3
Student marks:
Alice: 85
Bob: 95
David: 88


In [8]:
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
print("Set 1:", set1)
print("Set 2:", set2)
union_set = set1 | set2
print("Union of Set 1 and Set 2:", union_set)
intersection_set = set1 & set2
print("Intersection of Set 1 and Set 2:", intersection_set)
difference_set = set1 - set2
print("Difference of Set 1 and Set 2:", difference_set)
symmetric_difference_set = set1 ^ set2
print("Symmetric Difference of Set 1 and Set 2:", symmetric_difference_set)


Set 1: {1, 2, 3, 4, 5}
Set 2: {4, 5, 6, 7, 8}
Union of Set 1 and Set 2: {1, 2, 3, 4, 5, 6, 7, 8}
Intersection of Set 1 and Set 2: {4, 5}
Difference of Set 1 and Set 2: {1, 2, 3}
Symmetric Difference of Set 1 and Set 2: {1, 2, 3, 6, 7, 8}


In [9]:
def find_largest(numbers):
    if not numbers:
        return None  
    largest = numbers[0]
    for number in numbers:
        if number > largest:
            largest = number
    return largest
sample_list = [12, 45, 67, 23, 89, 54]
largest_number = find_largest(sample_list)
print("The largest number in the list is:", largest_number)


The largest number in the list is: 89


In [10]:
squares_of_even_numbers = [x**2 for x in range(1, 21) if x % 2 == 0]
print(squares_of_even_numbers)


[4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


In [11]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
product = (lambda x, y: x * y)(num1, num2)
print(f"The product of {num1} and {num2} is {product}")


Enter the first number:  6
Enter the second number:  4


The product of 6.0 and 4.0 is 24.0


In [14]:
import numpy as np
one_d = np.array([1, 2, 3, 4, 5])
print("One-dimensional array:")
print(one_d)
print("Shape:", one_d.shape)
print("Dimensions:", one_d.ndim)
two_d = np.array([[1, 2, 3],[4, 5, 6]])
print("Two-dimensional array:")
print(two_d)
print("Shape:", two_d.shape)
print("Dimensions:", two_d.ndim)
three_d = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])
print("Three-dimensional array:")
print(three_d)
print("Shape:", three_d.shape)
print("Dimensions:", three_d.ndim)

One-dimensional array:
[1 2 3 4 5]
Shape: (5,)
Dimensions: 1
Two-dimensional array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Three-dimensional array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3


In [16]:
import numpy as np
array = np.random.randint(1, 101, (5, 5))
print("Generated 5x5 Array:")
print(array)
print("Element at row 2, column 3:", array[1, 2])
print("First row:", array[0])
print("Last column:", array[:, -1])
print("Sub-array (first 3 rows, first 2 columns):\n", array[:3, :2])
print("All even elements:", array[array % 2 == 0])

Generated 5x5 Array:
[[54 40 94 21 40]
 [31 63 16 70 87]
 [15 83 21 77 84]
 [67 22 70  2 65]
 [66  5 89 43 85]]
Element at row 2, column 3: 16
First row: [54 40 94 21 40]
Last column: [40 87 84 65 85]
Sub-array (first 3 rows, first 2 columns):
 [[54 40]
 [31 63]
 [15 83]]
All even elements: [54 40 94 40 16 70 84 22 70  2 66]


In [20]:
import numpy as np
array_4x4 = np.random.randint(0, 10, (4, 4))  
print("Generated 4x4 Array:")
print(array_4x4)
print("Top-left 2x2 sub-array:", array_4x4[:2, :2])
print("Bottom-right 2x2 sub-array:", array_4x4[2:, 2:])
print("Second row:", array_4x4[1, :])
print("Third column:", array_4x4[:, 2])

Generated 4x4 Array:
[[9 8 9 4]
 [3 9 8 3]
 [3 2 4 2]
 [5 9 1 7]]
Top-left 2x2 sub-array: [[9 8]
 [3 9]]
Bottom-right 2x2 sub-array: [[4 2]
 [1 7]]
Second row: [3 9 8 3]
Third column: [9 8 4 1]


In [23]:
array_2d = np.arange(1,13).reshape(6,2)
array_3d = array_2d.reshape(2,3,2)
print("Generated 2D Array:")
print(array_2d)
print("Reshaped 3D Array:")
print(array_3d)
flattened_array = array_3d.flatten()
print("Flattened Array:", flattened_array)

Generated 2D Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Reshaped 3D Array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [24]:
array_3x3 = np.arange(1,10).reshape(3,3)
array_1x3 = np.array([10,20,30])
result = array_3x3 + array_1x3
print("Generated 3x3 Array:")
print(array_3x3)
print("One-dimensional Array:")
print(array_1x3)
print("Result after Broadcasting:")
print(result)


Generated 3x3 Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
One-dimensional Array:
[10 20 30]
Result after Broadcasting:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [26]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
addition = A + B
subtraction = A - B
multiplication = A * B
division = A / B
print("Array A:", A)
print("Array B:", B)
print("Element-wise Addition:",addition)
print("Element-wise Subtraction:",subtraction)
print("Element-wise Multiplication:",multiplication)
print("Element-wise Division:",division)


Array A: [[1 2 3]
 [4 5 6]]
Array B: [[ 7  8  9]
 [10 11 12]]
Element-wise Addition: [[ 8 10 12]
 [14 16 18]]
Element-wise Subtraction: [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise Multiplication: [[ 7 16 27]
 [40 55 72]]
Element-wise Division: [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [28]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Math": [85, 78, 92],
    "Science": [88, 74, 90],
    "English": [82, 80, 85]
}
df = pd.DataFrame(data)
df["Total"] = df["Math"] + df["Science"] + df["English"]
def assign_grade(total):
    if total >= 250:
        return "A"
    elif total >= 220:
        return "B"
    elif total >= 190:
        return "C"
    else:
        return "D"
df["Grade"] = df["Total"].apply(assign_grade)
print(df)


      Name  Math  Science  English  Total Grade
0    Alice    85       88       82    255     A
1      Bob    78       74       80    232     B
2  Charlie    92       90       85    267     A
